[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oauth4cli"
version = "0.2.0"
authors = [
  { name="Andreas Rühl", email="andreas.ruehl@gmail.com" },
]
description = "The most straight forward way of using standard python libraries for a authorization code flow via Browser for the CLI."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'flask',
    'requests',
    'requests-oauthlib',
    'werkzeug',
]

[project.urls]
"Homepage" = "https://github.com/aruehl/oauth4cli"
"Bug Tracker" = "https://github.com/aruehl/oauth4cli/issues"
